Feat delete ratings comments
interglobalvision/applaya pull request #105
Opened 2016-11-02 00:35 UTC by mixcas

When a committee user is deleted all ratings related to that user are deleted and the applications affected get avg. rating recalculated.

When an admin or committee user is deleted all comments related to that user are deleted too.

2016-11-04 22:25 UTC, mixcas commented
BUMP

2016-11-07 19:50 UTC, varffs requested changes
Surplus code needs cleaning I think

2016-11-07 19:50 UTC, varffs commented on app/imports/api/methods/commentsMethods.js
> +  let ratedApplicationsIds = _.map(userComments, comment => comment.applicationId);
why do you do this here? These are applications with comments not ratings. And you don't use this variable later in the comment?

2016-11-07 20:20 UTC, mixcas commented
Ready

2016-11-07 20:55 UTC, varffs approved these changes

2016-11-07 20:55 UTC, merged